from .constants import (
    INSTRUCTION_TEMPLATE as INSTRUCTION_TEMPLATE,
    QUESTION_TEMPLATE as QUESTION_TEMPLATE,
    ANSWER_TEMPLATE as ANSWER_TEMPLATE,
    PROMPT_TEMPLATE as PROMPT_TEMPLATE,
)
